driver:
  name: ec2
  aws_ssh_key_id: aws-adamscharf
  iam_profile_name: ecsInstanceRole
  instance_type: t2.micro
  region: us-east-1
  security_group_ids: ["sg-cc1fb6b6"]
  subnet_id: 	subnet-48024e62
  tags:
    Name: demo
    Hello: world

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  username: ec2-user
  ssh_key: <%= ENV['PERSONAL_AWS_PRIVATE_KEY_PATH'] %>

platforms:
  - name: amazon-linux
    driver:
      image_id: ami-275ffe31


suites:
  - name: default
    run_list:
  - name: web
    run_list:
      - recipe[test::apache]
